### ISSUE TITLE
How to open a folder with an application whose request was intercepted from Proxyman?

### ISSUE THREAD

**Issue by Drovosek01** [ProxymanApp/Proxyman#1022]
### Proxyman version? (Ex. Proxyman 1.4.3)
2.33.0

### macOS Version? (Ex. mac 10.14)
macOS 10.14.6

![image](https://user-images.githubusercontent.com/29478700/136667460-f38b897f-a4df-40f2-8ba3-be976275200d.png)

I am interested in the ability to open the folder in the Finder in which the application/process whose request was intercepted is located. I tried to right-click on the application icon in the line with the request in Proxyman, but I did not find an item there to open the folder with this application/process.

If there is such or similar functionality, then please tell me how to do it.

If there is no such functionality, then please add it. (It would also be convenient to use the item "Copy the path to the application/process" to then paste into the terminal)

**Comment by NghiaTranUIT** [comment]
@Drovosek01 You can do it by finding the app on the Left panel -> Right-click -> Show in Finder 👍 

<img width="881" alt="Screen_Shot_2021-10-10_at_12_25_09" src="https://user-images.githubusercontent.com/5878421/136683546-ac2fb6d1-932c-4c43-83b1-6e8f029f9e70.png">

Sorry if it's hard to discover, but we could not add this item to the right menu context in the main view, because there are already had a lot of buttons 🙌
