### ISSUE TITLE
Applications and traffic not visible

### ISSUE THREAD

**Issue by duraki** [ProxymanApp/Proxyman#104]
### Which Proxyman version are you using? (Ex. Proxyman 0.5 (200))

Latest update; `1.3.4.1`

### What OS Version are you using? (Ex. mac 10.13)

`MacOS 10.14.3`

### Steps to reproduce this issue
  
* Update to latest version from previous one (through app).
* Restart application.  
* **All** traffic not showing any app.
* **Adding application** does not show any visible application.

### Screenshots (optional)

![Screenshot 2019-04-07 at 22 13 13](https://user-images.githubusercontent.com/5892610/55689280-e25ee080-5982-11e9-890b-a3152e9fdab2.png)
  
Can't add any logged info cause #105.

**Comment by NghiaTranUIT** [comment]
Hey @duraki,

I'm so sorry for this inconvenience about last version.

I've fixed and released Proxyman 1.3.4.2 (https://s3.us-east-2.amazonaws.com/proxyman/1342/Proxyman_1.3.4.2.dmg) or you can update directly from the app.

The reason is that the new scripts didn't executed correctly in some computers, but it works on my machine 🐞, so I wasn't aware of it.

**Comment by duraki** [comment]
Works fine! Thanks for the update.
