### ISSUE TITLE
Feature request: Alphabetically sort pinned items/segments/endpoints

### ISSUE THREAD

**Issue by sundeepgupta** [ProxymanApp/Proxyman#1108]
I find myself having to hunt for pinned segment/endpoint because it looks like that lists gets populated on time of occurrence. It would be nice if it was deterministically the same and alphabetical seems to be the expected sort behaviour.

**Comment by NghiaTranUIT** [comment]
@sundeepgupta you can do it by right-clicking on the Domain / App folder -> Sort by Alphabet

<img width="384" alt="Screen Shot 2022-01-13 at 07 34 59" src="https://user-images.githubusercontent.com/5878421/149244907-a0016c7d-1f26-47f3-8682-646bdba8ebb5.png">

**Comment by sundeepgupta** [comment]
Oh I see, but it's not sorting the nested segments/endpoints, just the top level

**Comment by NghiaTranUIT** [comment]
Thanks. I will fix it 😄

**Comment by NghiaTranUIT** [comment]
@sundeepgupta here is your Beta build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_3.0.0_Fix_order.dmg

Sorry for the delay because I was busy implementing other features in [Proxyman 3.1.0](https://github.com/ProxymanApp/Proxyman/milestone/128) 👍. It's done and I gonna release on this week 😄  

<img width="370" alt="Proxyman Alphabetically sort" src="https://user-images.githubusercontent.com/5878421/153115491-3d9a25a1-546f-498c-8b87-abbd0ddf7873.png">

**Comment by sundeepgupta** [comment]
Amazing - thank you!
