### ISSUE TITLE
Don't see any request to nginx (local or dockerised)

### ISSUE THREAD

**Issue by indapublic** [ProxymanApp/Proxyman#1112]
### Proxyman version? (Ex. Proxyman 1.4.3)

Version 2.35.4 (23540)

### macOS Version? (Ex. mac 10.14)

11.6 (20G165)

### Steps to reproduce 

1. Open Proxyman
2. Open Google Chrome
3. Open http://127.0.0.1:8080/ (local) or http://127.0.0.1:10000 (dockerised)

### Expected behavior

See request in Proxyman

### Screenshots (optional)

<img width="1408" alt="image" src="https://user-images.githubusercontent.com/856260/149493185-2513fd5c-9dbe-437b-8c43-b35e9264386b.png">

What I did wrong?

**Comment by indapublic** [comment]
Thanks for so quick response, @NghiaTranUIT ! Works like a charm. What if I'm want to send those requests from another machine in my local network (e.g. http://10.0.88.188:10000)?

**Comment by NghiaTranUIT** [comment]
Sorry, but I don't understand how to "Send a request from another machine to my local network" 🤔 ?

**Comment by indapublic** [comment]
I have two machines in my local network at home. I want to open website (which hosted on my machine #1 with proxyman) from machine #2. Some confused how I can to use `localhost.proxyman.io` in this case.

**Comment by NghiaTranUIT** [comment]
It's tricky:

Let assume that the second machine it's your iPhone. Now, you would like to use iPhone to access a server (http://10.0.88.188:10000), which hosts on your Macbook + Proxyman.

From what I remember, you can easily do it.

1. Open Proxyman on your Macbook. Make sure you can visit your website by using http://localhost.proxyman.io:10000
2. Get your iPhone -> Setting app -> Wifi (Make sure they are in the same network) -> Proxy -> Set an IP and Port to your Mac Machine.

You can find the IP and Port in Proxyman Certifiacte menu -> Install on iOS -> Physical Device -> Step 2 => (You don't need to do step 3,4,5 ).

3. ON your iPhone -> Open Safari -> http://localhost.proxyman.io:10000 -> It will work


-----------
If you would like your alias name, it's trickier, since you have to set up a Share Network. Read more at https://stackoverflow.com/a/3132119/3127477

-------------

For the second Mac, you can do the same thing as the iPhone. Change the Wifi Proxy (Network -> Wifi -> Advanced -> Proxies tab).

**Comment by indapublic** [comment]
Awesome! Thanks @NghiaTranUIT Sorry for dumb questions.
