### ISSUE TITLE
Folders/Containers for Remote Mapping to allow batch enabled/disable etc.

### ISSUE THREAD

**Issue by iangregsondev** [ProxymanApp/Proxyman#1119]
### Proxyman version? (Ex. Proxyman 1.4.3)
3.0
### macOS Version? (Ex. mac 10.14)
latest

### Steps to reproduce 

I hope you don't mind me suggesting an improvement for mappings.

It would be nice to be able to separate into folders the Remote Mappings.

For example, I have this..

![image](https://user-images.githubusercontent.com/2370364/150687312-f91ca3ed-ed38-4bc1-b7b7-21256bbf6a2d.png)

There are currently 2 rules that i need for this specific task, it would be great if we could make them part of a FOLDER / Container... so that we can apply the rules as a whole and disable them as a whole.

Also, it would be great to be able to have access to these rules on the toolbar, maybe ?? Somewhere where there is easy access rather than opening up a model to enable / disable them.

Thanks! Great product!  Glad I purchased it, its saving me so much work!

Oh, one question, its probably not possible but I am redirecting traffic from a Browser plugin, I have 2 brave browsers open, 1 is my normal browser and the other is a completely different user that i use for debugging...

Is there no way to only view things from that browser window ? I suppose not ?

I am referring to this

![image](https://user-images.githubusercontent.com/2370364/150687542-197d6200-6bb0-43b4-a791-67d2177275c5.png)

All messages for plugins from the main browser window and also my other browser window fall under this category

Thanks again!

**Comment by NghiaTranUIT** [comment]
Thanks for your suggestion @iangregsondev. I'm happy to receive all feedback 🌮 

> There are currently 2 rules that i need for this specific task, it would be great if we could make them part of a FOLDER / Container... so that we can apply the rules as a whole and disable them as a whole.

This Folder feature is in our road map (#713), but it has a delay due to its complexity. We've partially implemented it, but it hasn't satisfied our expectations yet.

> Also, it would be great to be able to have access to these rules on the toolbar, maybe ?? Somewhere where there is easy access rather than opening up a model to enable / disable them.

You can quickly open the Remote Window by either:
1. Use Shortcut Option + Command + R -> Then, Command + T to enable/disable a particular rule.
2. Right-click on the toolbar -> Customize the Toolbar -> Drag and drop the Map Remote to the toolbar. By doing it, you can easily click on it to disable/enable the entire tool.

<img width="431" alt="Screen Shot 2022-01-24 at 10 40 10" src="https://user-images.githubusercontent.com/5878421/150718344-90dad558-373c-4975-bc73-417c49ce0d2e.png">

> Also, it would be great to be able to have access to these rules on the toolbar, maybe ?? Somewhere where there is easy access rather than opening up a model to enable / disable them.

Sorry, we haven't supported this feature yet. (Shortcut to enable/disable a certain rule), but your justification is reasonable.

> Oh, one question, its probably not possible but I am redirecting traffic from a Browser plugin, I have 2 brave browsers open, 1 is my normal browser and the other is a completely different user that i use for debugging...
> Is there no way to only view things from that browser window ? I suppose not ?


Since they are the same Brave bundle identifier, Proxyman categorized it in the same application. Proxyman doesn't know if it's from your primary or secondary account, unfortunately.

I suggest that you can use two different Web Browsers, such as Brave + Chrome.

> Thanks! Great product! Glad I purchased it, its saving me so much work!

Thanks for supporting Proxyman team ❤️ 😄

**Comment by iangregsondev** [comment]
Thanks!, Yep I just added the Map local/remote into the toolbar,  that's nice, I can use it as a kill switch.

Thanks once again, I will close this now. Look forward to future updates.

Thanks!
