### ISSUE TITLE
GRPC support

### ISSUE THREAD

**Issue by ColtonIdle** [ProxymanApp/Proxyman#1127]
Hello, in the bug reports here it looks like protobufs are supported but grpc is not. Is that still the case?

My use case is that I use firestore and I want to inspect the network traffic: here is the proto file for firestore https://github.com/googleapis/googleapis/blob/master/google/firestore/v1/firestore.proto

**Comment by NghiaTranUIT** [comment]
You're right, Proxyman doesn't support GRPC out of the box since gRPC requires a MitM gRPC server in order to intercept it. It's more complicated than HTTP/HTTPS Mitm Proxy.

We had a discussion before regarding the Firebase GA (https://github.com/ProxymanApp/Proxyman/issues/449#issuecomment-978798839)

Here is a work around solution: https://github.com/ProxymanApp/atlantis#2-my-app-use-grpc

**Comment by ColtonIdle** [comment]
Thanks. I guess I was curious if I missed something new. I write android apps so atlantis doesnt help me too much. Closing for now 😭 . thanks for the reply
