### ISSUE TITLE
Bug Capturing traffic iOS Minecraft & Monster Legends

### ISSUE THREAD

**Issue by jesus-mg-ios** [ProxymanApp/Proxyman#1162]
### Steps to reproduce 

Install in iOS device the Proxyman certificate and trust into it. 
Then start to capturing traffic.

* Run Monster Legends (Error: Seems like the connexion was ended by the client) Not reproduced with Proxyman iOS App.
* Run Minecraft (Log in to it, Error: Cannot Logging) Not reproduced with Proxyman iOS App.

In both cases response is not enabled (Not intercept the traffic only forward it.)

### Expected behavior
 Monster Legends should work as expected
 You can log in into an account with minecraft.

**Comment by NghiaTranUIT** [comment]
Hey @jesus-qt, thanks for your report.

Unfortunately, It's not a bug from Proxyman. I suspect that these apps are protected by using SSL Pinning. It's designed to prevent Proxyman or other debugging proxy apps to intercept their HTTPS traffic.

There is no solution to bypass the SSL Pinning unless you have a certificate key.

You can read more at https://proxyman.io/posts/2019-11-15-Can-we-bypass-ssl-pinning

**Comment by jesus-qt** [comment]
Hey @NghiaTranUIT, thanks for your support, but you didn't answer me. Please, pay attention.

I'm only forwarding the traffic through the Proxyman app, I'm not doing a MIT, so I don't want to decrypt the traffic. For this, Proxyman shouldn't intercept the handshake ssl, so the ssl pinning not affect to this scene.

Please, let me know if it's all clarified.

**Comment by NghiaTranUIT** [comment]
Ah, I missed reading it. I'm downloading the Monster Legend app on my phone and try to reproduce it now 👍

**Comment by jesus-qt** [comment]
@NghiaTranUIT any news about why the behaviour is different from the network extension vs the macOS App?

**Comment by NghiaTranUIT** [comment]
I tried Monster Legend and it works totally fine after I set the HTTP Proxy to Proxyman Mac, but not Enable SSL Proxying.

- Bunch of Monster Legend HTTP Request that I can see it in the plain text
<img width="1905" alt="Screen Shot 2022-03-08 at 09 37 02" src="https://user-images.githubusercontent.com/5878421/157155443-74d18726-e1b8-4546-867b-447bce27a6cd.png">

- The game work fine. I'm able to play the game as usual.
![IMG_0614](https://user-images.githubusercontent.com/5878421/157155514-fee1959e-260a-4b39-906e-73f1e9604ab9.PNG)

---------------------------
I could not test with Minecraft since it's required to pay upfront.

---------------------
It seems that you have to see the DNS to 1.1.1.1 or 8.8.8.8 in both Mac and iOS devices:
- on macOS: System Preference -> Network -> Wifi -> DNS -> Set 1.1.1.1
- on iOS: Setting -> Wifi -> Your wifi hotspot -> DNS -> Manual -> Set 1.1.1.1

Then try again 👍 

------------------------
Second question: After you change the HTTPS Proxy from your iOS devices, are you able to visit the Internet? By opening https://google.com on the Safari app?

**Comment by jesus-qt** [comment]
Hey @NghiaTranUIT, thanks for the support. I see that in some devices iOS this doesn't work the first time that you open the app. 
Also, in Proxyman iOS, the error not persists because once the monster legends connection is done (social point and download the translations), the proxy crash, so yeah with the retry goes because the vpn is down. If the vpn is up, the game doesn't load...

https://user-images.githubusercontent.com/85997060/157916286-02a356c9-cc1f-404d-9856-b044f7279843.mp4
