### ISSUE TITLE
Hello! Can you add Chinese languages for Proxyman? Thank you very much!

### ISSUE THREAD

**Issue by Code317** [ProxymanApp/Proxyman#1165]

**Comment by NghiaTranUIT** [comment]
Sorry, but we don't have any plan to support Chinese Localization at this moment 👍 

Just wondering: 
1. Does the English language causes trouble when you use the app? 🤔  
2. How many teammates/colleagues have the same language problem?

I'd like to understand how much it affects your daily work. If it's huge, we can consider support Chinese soon.

**Comment by VaslD** [comment]
Also +1 on Chinese (preferably Simplified Chinese) support.

English doesn't *cause trouble* as using a piece of software isn't daily communication. From my understanding, as long as we have a certain level of English skill, or at the very least, have learned what-this-big-red-button-does, we don't necessarily need to understand every word and all grammar used on the interface.

If it's not too much trouble, localization (and I mean proper localization, unlike Microsoft's ML approach to their Windows API documentation site) is always appreciated. It boosts productivity and widens the audience of your software entirely. Nothing beats reading in your native language.

Personally I have recommended Proxyman to many colleagues and friends, and I can tell that some favors other software because those products have proper localization. They only use Proxyman if the feature is unavailable in competing software (e.g. Atlantis support). And even then they will have two network debuggers open and switch to the other one as soon as Atlantis is no longer needed.

I understand that Proxyman is freemium and localization may not come cheap from a business standpoint. If that's the case I recommend considering community solutions like Crowdin or Transifex.
