### ISSUE TITLE
Setting `*` in SSL Proxying Tool's "Enable" list causes all subsequent HTTP requests to return SSL Handshake error

### ISSUE THREAD

**Issue by ASchneider-GitHub** [ProxymanApp/Proxyman#1183]
### Proxyman version? (Ex. Proxyman 1.4.3)
v3.2.0 (30200)
### macOS Version? (Ex. mac 10.14)
macOS Big Sur v11.0.1
### Steps to reproduce 

1. Install and launch Proxyman
2. Certificate > Install Certificate on this Mac
3. On Android device, install SSL certificate from http://proxy.man/ssl
4. Connect device to WiFi, traffic starts flowing in correctly.
5. Tools > SSL Proxying List
6. Add new wildcard, setting only a `*`
7. Traffic completely stops flowing through, with every request returning:
```
SSL Handshake Failed
handshakeFailed(NIOSSL.BoringSSLError.sslError([Error: 268436502 error: 10000416:SSL routines:OPENSSL_internal:SSLV3_ALERT_CERTIFICATE_UNKNOWN)
```

### Expected behavior
All domains should have SSL Proxying enabled by default after wildcard is applied

### Screenshots (optional)
N/A

**Comment by NghiaTranUIT** [comment]
Sorry, if you're using Android + Proxyman, it requires doing a few important steps.

Here is the guideline: https://docs.proxyman.io/debug-devices/android-device

Make sure you trust the certificate in step 4 and change the network config in step 5.

Otherwise, Proxyman could not capture traffic from your Android devices.

**Comment by ASchneider-GitHub** [comment]
Ahh I see the issue. I didn't see the step saying you can only see proxy requests from apps you own, due to having to edit the manifest file. Sorry for the frivolous Issue.
