### ISSUE TITLE
Scripting & Map Local features on iOS

### ISSUE THREAD

**Issue by storytellar** [ProxymanApp/Proxyman#1186]
I've been waiting so long, please release it... or Map Local at least. :(

**Comment by NghiaTranUIT** [comment]
I did a little experiment on the Editor on iOS app (It's for Map Local and Scripting), but the user experience is really bad. The reason is CodeMirror 5, which is powered the Editor, doesn't work well on mobile. Thus, I postpone implementing it 👍 

I highly suggest using Map Local and the Script on macOS, since it's easer I believe @storytellar

**Comment by storytellar** [comment]
It doesn't relevant to the Editor. We just hope the function will work well. About the code editor - maybe leave it later, it's okay. It would be great if dev team upgrade Local Maps or Scripting function to iOS. ^^!

**Comment by NghiaTranUIT** [comment]
FYI, the Map Local tool is available and the iOS app.
