### ISSUE TITLE
Last few releases not as reliable as older builds?

### ISSUE THREAD

**Issue by ilendemli** [ProxymanApp/Proxyman#1246]
### Proxyman version?
3.5.0 vs. 3.2.0

### macOS Version?
macOS Monterey 12.3.1 (21E258)

### Steps to reproduce
I have to use a proxy when connected to my company VPN (Checkpoint VPN), and I chose to use ProxyMan for this.
Not sure since when I have this Issue (3.4.0 and 3.5.0 have this Issues for sure), but when I enable ProxyMan, I get a bunch of Internal Error with Status Code 999 initially. After some time it works as expected, by itself. I can't reproduce the Issue with 3.2.0.

**Comment by NghiaTranUIT** [comment]
From what I understand, there is no major change in the Proxy Core from Proxyman 3.5.0 and Proxyman 3.2.0. It's hard to pinpoint precisely whether or not the latest build is less reliable than the old build because the Checkpoint VPN is involved.

Basically, Proxyman might not work well with these VPNs apps, and I'm not sure if it's possible to fix it in our app.

I suppose that you might try:
1. Use the latest build 3.5.0
2. Reset the Certificate in Preference -> Delete the Certificate
3. Try again if you get 999 error

**Comment by ilendemli** [comment]
As I said, It worked before suddenly developing these issues. I reverted back to 3.2.0 and then back to 3.5.0. Resetting the Certificates did not change anything. I will continue observing for the next few days and report back if there is anything worth mentioning.

**Comment by NghiaTranUIT** [comment]
Thanks. I would keep an eye on this issue too 👍

**Comment by ilendemli** [comment]
I am not quite sure why this happens, but it may not be related to ProxyMan. Closing it for now.
