### ISSUE TITLE
No logs seen on emulators with iOS >= 15 and url in the form https://asfsaf-test-y5adsfas3a-ew.a.run.app with a valid ssl cert

### ISSUE THREAD

**Issue by shadowsheep1** [ProxymanApp/Proxyman#1268]
### Proxyman version? (Ex. Proxyman 1.4.3)

3.6.0 (30600)

### macOS Version? (Ex. mac 10.14)

12.4

### Steps to reproduce 

Use Xcode 13.4.1 and an emulator with iOS 15.5 (certificates all right, on mac and on device).

With an iOS 15.5 devices no log are captured. Sometimes all start successfully, but suddenly there something wrong with the inspection. And no more logs are captured.

![Screen Shot 2022-06-27 at 10 51 04](https://user-images.githubusercontent.com/16268789/175901468-339d669c-47e8-4fca-9947-13636e0d284b.png)

![Screen Shot 2022-06-27 at 10 51 43](https://user-images.githubusercontent.com/16268789/175901474-d345b4e9-9b80-40a8-8fec-643e70cd77cc.png)

With and iOS with iOS 14.0 logs are captured.

![Screen Shot 2022-06-27 at 10 48 18](https://user-images.githubusercontent.com/16268789/175901435-ad2f569b-3335-4002-ac25-89a82cd5bad3.png)

### Expected behavior

See logs of my application in any iOS version.

### Gut feeling

It seems that the problem is the test url that is in the form `https://asfsaf-test-y5adsfas3a-ew.a.run.app` (but the certificate is valid, and in fact all works fine on emulators with iOS < 15)

**Comment by shadowsheep1** [comment]
Hi @NghiaTranUIT If you mean that the app makes the request to the webserver, even without `print()` (I've already some log on my app side) I can confirm you that the app make successfully api calls to the seveers 'cause it works like a charm, only I can see any request on proxyman.

**Comment by shadowsheep1** [comment]
If I change the api endpoint with the production one, I can get the logs:

![Screen Shot 2022-06-27 at 14 18 49](https://user-images.githubusercontent.com/16268789/175940572-82f8b369-0031-4e3e-b0c8-822850408927.png)

There's some proxyman log I can send you with a pm?

It seems that this behaviour is occurring only with the test url (with a valid ssl cert) and an iOS 15.5 emulator.

![image](https://user-images.githubusercontent.com/16268789/175941158-b69c6709-801e-41bd-a479-7a480e23fdab.png)

**Comment by shadowsheep1** [comment]
@NghiaTranUIT this way is working
![Screen Shot 2022-06-27 at 15 14 46](https://user-images.githubusercontent.com/16268789/175950381-93cf6dca-d175-443a-af96-5fcb966551c8.png)
 
I can see the request under proxyman domains section

**Comment by NghiaTranUIT** [comment]
So, your test URL is working and Proxyman can capture it.

If you don't mind, please try iOS 15.5 on Physical devices or different type of Simulator (such as iPad)

**Comment by NghiaTranUIT** [comment]
Yes, I suppose so if this test URL displays on Proxyman from iOS 14, there is no reason that it doesn't appear on Proxyman.

Except its an error, but you've confirmed that your app is still working.

**Comment by shadowsheep1** [comment]
My app is working fine. I debug it with Proxyman from more than 2 years. 🍻

**Comment by shadowsheep1** [comment]
@NghiaTranUIT all except the combinatioin of `testurl`+`emulator with ios15`. Is should be nice to know why, but I think I can live with this weight on my heart ;). I close the issue 'cause I don't think this is a proxyman issue, but of the pair test url and ios 15 (emulator). Thanks.

**Comment by timothy-pratama** [comment]
Hi, I'm also facing exactly the same issues. One thing that I can confirm the same between my case and @shadowsheep1 is that when the proxy tries to send the `CONNECT` request to the server, it's getting SSL Handshake failed. Based on https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/CONNECT, my guess is since the `CONNECT` request is failed, maybe iOS simulator 15 will directly connect to the server without using the proxy, and that's why the network traffic doesn't show in the proxy as well. As to why the `CONNECT` request is getting that error, I also have no idea.

I can confirm that this issue only happens in the iOS 15 simulator + certain domain combinations, not in the Proxy man itself. I've tried to use another proxy and the result is also the same. The only solution that I find working is just by downgrading the iOS simulator to < 15 and everything working now.

Hope this will give some insight. Thanks!

**Comment by NghiaTranUIT** [comment]
@timothy-pratama Is your iOS app a native app, or Flutter, React Native?

**Comment by timothy-pratama** [comment]
> @timothy-pratama Is your iOS app a native app, or Flutter, React Native?

It's native apps, and the weird thing is sometimes the CONNECT request is successful, and sometimes the CONNECT request keeps getting the SSL handshake failed. And sometimes the CONNECT request is only successful when it's the fresh install only. But I'm certain that this issue is not caused by Proxy Man 🙏🏻

**Comment by shadowsheep1** [comment]
I can confirm that. I'll try to file an issue at Apple side.

**Comment by shadowsheep1** [comment]
@timothy-pratama do you have a public url I can share with apple with a sample app to test it?

**Comment by shadowsheep1** [comment]
@timothy-pratama are you using kotline-native (ktor) for networking?

**Comment by timothy-pratama** [comment]
@shadowsheep1 unfortunately I don't have any public URL with a sample app to test it as well 🙏🏻. I'm using native swift for the networking (using alamofire)

**Comment by NghiaTranUIT** [comment]
If Charles Proxy can capture this traffic, it means it's a bug from Proxyman.

if not, maybe it's from Apple side 😄

**Comment by timothy-pratama** [comment]
Proxy Man can only capture the `CONNECT` request that gets the SSL handshake failed error when the bug happened. After that error, there is no more traffic coming from the same domain captured in Proxy Man. I have tried to use Charles Proxy, and the result is the same with Proxy Man. The only solution was to downgrade my iOS simulator to 14.5 and everything works fine now (with the same code) 😀

**Comment by NghiaTranUIT** [comment]
Hey guys, I suppose that Alamofire/URLSession might use the cached response version from disks, so it never hits the server => Proxyman never catches it.

If you don't mind, please delete your app on the Simulator and try again.

**Comment by timothy-pratama** [comment]
Actually I have tried deleting the app before. The logs will be shown only for the first time running the app (fresh install). After that, the next time I start my apps, the logs will no longer appears in proxy man again and I will get the same SSL handshake failed error. I have also suspected there is a cache mechanism that causes this, so I have tried to open a screen in the app that has not been opened before (so I assume there should be no cache yet for that screen), it still loaded successfully even though the log doesn't appear in Proxy Man

I'm still pretty sure it's something wrong in iOS 15 simulator because @shadowsheep1 has tried using a physical device running iOS 15 and doesn't get this error  https://github.com/ProxymanApp/Proxyman/issues/1268#issuecomment-1167357709

Thank you for replying @NghiaTranUIT 🙏🏻

**Comment by shadowsheep1** [comment]
@timothy-pratama are you still experiencing this issue? Actually today I'm able to proxy traffic with my iOS 15 simulator 🤷‍♂️

**Comment by NghiaTranUIT** [comment]
Some users report they have the same issue on iOS 15 Simulator too. It also happens on Charles Proxy.

The only way to fix it is using the iOS Real Devices or using the iOS 14 Simulator.

**Comment by shadowsheep1** [comment]
@NghiaTranUIT  I know,but today the issue disappears to me. I also filed an issue to Apple with Feedback Assistant, maybe they could help. The fun fuct is that today the issue is no more an issue for my URL. 🤷‍♂️

**Comment by timothy-pratama** [comment]
> Some users report they have the same issue on iOS 15 Simulator too. It also happens on Charles Proxy.
> 
> The only way to fix it is using the iOS Real Devices or using the iOS 14 Simulator.

Yes, I'm still facing it. But as @shadowsheep1 mentioned, this bug only happens in iOS 15 Simulators and it's intermittent too. So when the bug is gone, it will be working fine. But once the bug comes back, it will be buggy for quite some time. Not sure though what is the trigger

**Comment by shadowsheep1** [comment]
As mentioned above I filed an issue to Apple Dev Tools with Feedback Assistant posting device log, sample app, a video showing the issue and some more fancy stuff :) Let's see what they say. if they answer before iOS 16 😂, hoping iOS 16 doens't have this very same bug.

**Comment by piercifani** [comment]
Any news on this regard? It's really starting to look like a deal breaker here...

**Comment by NghiaTranUIT** [comment]
Sorry, @piercifani it's not a bug of Proxyman or Charles. It's the bug from iOS Simulator. If you use iOS Physica devices or iOS 14, the issue is gone 👍

**Comment by piercifani** [comment]
Hello @NghiaTranUIT,

Yes but I think that's not something they're going to fix. Have you considered spend a DTS ticket in order to have someone look at this? This way you could:

- Double check nothing's wrong on your end 
- There is no can't be workaround
- At least Apple Engineering takes a look at this and prioritises it.

Right now, this bug kind of defeats the purpose of Proxyman, and I know this is no fault of Proxyman... but still...

**Comment by robmathers** [comment]
Just chiming in here that I'm running into this as well. One build & run will work fine on the Simulator, and then the same (with no changes) will fail (networking works fine, but not capture in Proxyman). Seemingly happened around Xcode 13.4, but I'm not 100% sure. Interestingly, opening the same domain in Safari does capture it in Proxyman.

Would be nice if a DTS and Feedback (Radar) was opened, but a workaround would be great given iOS 16 seems to be worse off currently.

**Comment by NghiaTranUIT** [comment]
You can confirm it by using with physical devices @robmathers. All traffic should be captured. On the other hand, some are missing on iOS Simulator. Test with Charles Proxy too.

To would around with iOS Simulator, I highly recommend using Atlantis framework: https://github.com/ProxymanApp/atlantis

**Comment by robmathers** [comment]
Thanks, I can confirm it does work as usual with physical devices, but not working with simulators is a big bug. Just hoping that we can collectively raise this issue with Apple to make some noise 🤷‍♂️

The framework is a good workaround, but not necessarily a great option to require a whole new dependency, especially in a work project. Not your fault I realize, but definitely good if we could get a fix sorted via Apple.
