### ISSUE TITLE
scripting timeout

### ISSUE THREAD

**Issue by webuniverseio** [ProxymanApp/Proxyman#1275]
### Proxyman version? (Ex. Proxyman 1.4.3)
3.6.0
### macOS Version? (Ex. mac 10.14)
12.3.1
### Steps to reproduce 
Try scripting with this code
```
await new Promise(resolve => setTimeout(resolve, 10000))
```
### Expected behavior
Expect hanging request for 10s before other scripting logic will execute. Instead getting scripting error (I know JS engine doesn't support Promise, but then at least some js cases are not possible to implement)

**Comment by webuniverseio** [comment]
As a hack workaround I'm thinking of making a request to api which supports timeouts via parameters. Very hacky :D. It would be good to have a built in method like sleep(ms)

**Comment by NghiaTranUIT** [comment]
You get the error because `setTimeout` isn't implemented in the JavascriptCore. Meanwhile, it supports Promise.

For the `$http` func, the timeout at 10 seconds. Thus, it will work with `await $http.get('http://httpbin.org/delay/10')`, but you get timeout with `await $http.get('http://httpbin.org/delay/15')`

If you'd like to delay the request/response, you can simply use the `sleep()` function

```js
async function onResponse(context, url, request, response) {
  console.log("Start sleep");
  
  // Sleep 30 seconds
  sleep(30000);
  
  // Done
  return response;
}
```
Ref: https://docs.proxyman.io/scripting/snippet-code#response-delay-with-sleep-function

--------------
If it's not what you're looking for, please let me know 😄 

----------

I guess I should implement the `setTimeout` function soon 👍

**Comment by webuniverseio** [comment]
Thanks, my bad, I need to read the manual 😅
