### ISSUE TITLE
Broken styles in breakpoint window (too dark)

### ISSUE THREAD

**Issue by amorphius** [ProxymanApp/Proxyman#1291]
### Proxyman version? (Ex. Proxyman 1.4.3)
Version 3.6.2 (30620)

### macOS Version? (Ex. mac 10.14)
mac 12.3.1

### Steps to reproduce 
1. Create breakpoint rule
2. Make this breakpoint to be activated

### Expected behavior
The text and background should be in better contrast

### Screenshots (optional)
<img width="1168" alt="image" src="https://user-images.githubusercontent.com/1895127/177999124-b8af7a8b-b9c0-4bf3-95ca-b08f8625dcd9.png">

**Comment by NghiaTranUIT** [comment]
Look like the problem when you change the theme. Please try to re-open the app, it will fix it.

**Comment by NghiaTranUIT** [comment]
Ah, I'm able to reproduce your issue. To fix it, please use Dark Theme in System Preference -> Appearance -> Dark Theme.

I'm going to fix it and send you a Beta 👍

**Comment by NghiaTranUIT** [comment]
Hey @amorphius your issue is fixed: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_3.6.2_Fix_Breakpoint_Theme.dmg

### Screenshots

<img width="1089" alt="Screen Shot 2022-07-09 at 08 47 07" src="https://user-images.githubusercontent.com/5878421/178087996-e8551edc-5692-4b3c-81ac-41acd54c95d9.png">

**Comment by amorphius** [comment]
nice, it works, thank you!
