### ISSUE TITLE
Serious performance problems were encountered when using request filtering

### ISSUE THREAD

**Issue by chhpt** [ProxymanApp/Proxyman#1340]
### Proxyman version? (Ex. Proxyman 1.4.3)

3.8.0

### macOS Version? (Ex. mac 10.14)

macOS 12.5

### Steps to reproduce

No

### Expected behavior

No

### Screenshots (optional)

This is a gif show that filter input was stuck when i try to type 'dispatch'.

PS: 
- There are 100~200 request records
- There are some requests with large response.

![CleanShot 2022-08-26 at 18 41 41](https://user-images.githubusercontent.com/19288423/187023101-9631ffc9-c0da-4025-bb75-c0d26ab33bb6.gif)

**Comment by NghiaTranUIT** [comment]
Can you Specify the filter scope instead of using "All"?

For example:
- `/meta` can be used with URL Filter.

The problem is: All will evaluate all, including URL, Header, Body, Status Code, and Color in both Request & Response. On the other hand, two filters would x2 the number of operations. Thus, it can slow down the performance.

**Comment by chhpt** [comment]
@NghiaTranUIT I got it, thanks for your help.
