### ISSUE TITLE
Proxyman iOS - Filter by app (same as Proxyman macOS)

### ISSUE THREAD

**Issue by ptrkstr** [ProxymanApp/Proxyman#1367]
## Description
The home screen of the Proxyman iOS app shows network requests grouped by domain. It would be useful if there was an option to change this to view by App.

## Why this feature/change is important?
Usually when I'm inspecting traffic, I care about network requests coming from a single app and not about other domains. This can become frustrating when multiple apps use the same endpoint (i.e. google/facebook) and searching just by domain doesn't help. Proxyman macOS has this feature and it could be useful to have it on Proxyman iOS.

**Comment by NghiaTranUIT** [comment]
Sorry, but it's technically impossible. The iOS app is more strict in terms of security, so it's impossible to read the port via the `iptable`, which is how the macOS app is implemented.

On the other hand, Proxyman for iOS is a sandboxed app, so it doesn't allow to retrieve of some low-level data. Otherwise, the app might not pass the Apple Review.

**Comment by ptrkstr** [comment]
Thanks for replying so quickly @NghiaTranUIT. I understand the limitation is from Apple. I also did some research and looks like it's not possible to set up a Per-App VPN without MDM. I hope Apple adds this feature in the future.

**Comment by NghiaTranUIT** [comment]
Thanks for understanding @ptrkstr 🤝.  It would be great if Proxyman for iOS can show traffic from particular apps.

If Proxman expands to the Android app, I suppose that it's possible since Android OS is more open than iOS.
