### ISSUE TITLE
Filter error

### ISSUE THREAD

**Issue by thanhps42** [ProxymanApp/Proxyman#1369]
Link ví dụ: https://zozo.jp/shop/nike/goods/54405525/?did=111803012&rid=1003
Tìm ở đây thì ra:
![image](https://user-images.githubusercontent.com/11658963/191519987-472dae65-797e-484a-8a62-8cae95214a41.png)
Nhưng tìm ở đây thì không ra:
![image](https://user-images.githubusercontent.com/11658963/191520114-f26a6f33-3749-4194-ab0b-c9da2631f400.png)

**Comment by NghiaTranUIT** [comment]
It's odd why the Filter couldn't find the result on the Response Body 🤔 Will check out tomorrow and send a Beta fix 👍

**Comment by NghiaTranUIT** [comment]
@thanhps42 let;s check out this build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_3.10.0_Fix_Filter_Request_Response_Body.dmg

<img width="1976" alt="Screen Shot 2022-09-21 at 22 13 56" src="https://user-images.githubusercontent.com/5878421/191542878-94a50f0e-fdee-4fc0-af8a-e459ee71b85c.png">

The problem is because the Body is encoded with Japanese charset, so the original filter doesn't work well.

**Comment by thanhps42** [comment]
> @thanhps42 let;s check out this build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_3.10.0_Fix_Filter_Request_Response_Body.dmg
> 
> <img alt="Screen Shot 2022-09-21 at 22 13 56" width="1976" src="https://user-images.githubusercontent.com/5878421/191542878-94a50f0e-fdee-4fc0-af8a-e459ee71b85c.png">
> 
> The problem is because the Body is encoded with Japanese charset, so the original filter doesn't work well.

Fixed, thanks :D
