### ISSUE TITLE
Source List Panel cannot be width adjusted

### ISSUE THREAD

**Issue by philosopherdog** [ProxymanApp/Proxyman#1380]
## Description
Source List Panel cannot be width adjusted

## Steps to Reproduce

1. try to adjust the Source List Panel width

## Current Behavior
nothing happens!

## Expected Behavior
width adjusts

Note:
When I switch from `All` to `HTTP` or one of the others it allows me to adjust it but it goes back! Annoying
## Environment
Version 3.10.0 (31000)
MacOS 12.6

<img width="306" alt="Screenshot of Proxyman (2022-10-05, 13-38-50)" src="https://user-images.githubusercontent.com/530718/194125619-04cbc338-6aac-4acb-8ef3-f955d1a9ae49.png">

**Comment by NghiaTranUIT** [comment]
Sorry but I could not reproduce the issue on my Mac 15"

https://user-images.githubusercontent.com/5878421/194186431-8f3c9179-76a8-46a7-8a0a-62d2b992f943.mp4

Just wondering: What is the size of your Mac screen? I suppose that a small size + low resolution can cause the bug.

**Comment by philosopherdog** [comment]
Hey, I'm on a 16 inch M1. Here's a video. Usually I can't see this much of the side bar. I believe it has to do with long urls with lots of param.

https://user-images.githubusercontent.com/530718/194188774-bd1d2ccf-4378-474f-aa45-1f0963ebe68e.mp4

**Comment by NghiaTranUIT** [comment]
If you don't mind, please share with me the entire screenshot of the app. You can censor your data if you'd like.

I'd understand your current layout.

### The width of the Left column is limited
If the Request/Response panel is on the Vertical Mode, the left panel might not have enough room to resize.

![Screen_Shot_2022-10-06_at_08_09_34](https://user-images.githubusercontent.com/5878421/194191864-26cfe4ac-4f90-4307-b859-82a7e54b6951.jpg)

On the other hand, if I use Horizontal Layout, the Left column can easily be resized.

![Screen_Shot_2022-10-06_at_08_09_41](https://user-images.githubusercontent.com/5878421/194192592-1dcd4d36-caf5-4cc7-bea2-7fe81e77c004.jpg)

**Comment by philosopherdog** [comment]
https://youtu.be/QYnlUaX8huo

**Comment by NghiaTranUIT** [comment]
Thanks for the video @philosopherdog 

You couldn't resize the Left panel because there are a lot of Tab buttons on the Request & Response Panel.

![Screen_Shot_2022-10-14_at_07_27_28](https://user-images.githubusercontent.com/5878421/195735530-c7d0f399-0523-4893-9ec8-73ec1c089406.jpg)

Since the visibility of these buttons is high, it prevents the left panel to resize.

I suggest: either:
- Click on the `+` button on the Request/Response Panel
- Or Tools Menu -> Custom Previewer Tab

=> Unselect some unused tabs

It will let you have more space and allow you to resize.

----------------------------

 Meanwhile, I will find a solution to fix it. Maybe allow hiding some Tab buttons.

**Comment by philosopherdog** [comment]
Phew, Ok that makes total sense! Much appreciated.
