### ISSUE TITLE
I only see CONNECT HTTPS requests.

### ISSUE THREAD

**Issue by igr** [ProxymanApp/Proxyman#1519]
I am only capturing the `CONNECT` requests, from the HTTPS, eg.:

![CleanShot 2023-01-31 at 17 59 08](https://user-images.githubusercontent.com/2280001/215830697-649c9e1d-3d54-4d80-b303-34466ec24a76.png)

What am I doing wrong?

**Comment by igr** [comment]
Solved by adding a wildcard.

**Comment by NghiaTranUIT** [comment]
@igr if you use the wildcard `*`, your MacBook could be slowed because Proxyman tries to intercept all data. Please open the Tools -> SSL Proxying List -> Remove the `*`

---------------

`CONNECT` means the requests are proxies and aren't intercepted.

You have to select the request -> Right Click -> Enable SSL Proxying.

Or simply click on the "Enable on this domain" in the Response Panel.

![Screenshot_2023-02-01_at_08_16_02](https://user-images.githubusercontent.com/5878421/215921329-3aad5e2a-b2c6-4a79-a7e6-670be407a9f2.jpg)

Then, you can see the HTTPS traffic.
