### ISSUE TITLE
Uncontrolled automatic sending of requests

### ISSUE THREAD

**Issue by 907352qq** [ProxymanApp/Proxyman#1651]
## Description
I have found a problem, when I request a url that does not exist, the software will automatically send the request repeatedly, for example, if I request "http://127.0.0.1:9090" in my browser. I don't know if it's a problem with my operation or with the software, but I'd appreciate an answer!

**Comment by NghiaTranUIT** [comment]
@907352qq Proxyman doesn't send the request repeatedly. If it's an invalid URL, it just sends back the response and stops the socket.

Do you have any screenshot to show that it's repeated?

**Comment by 907352qq** [comment]
![image](https://github.com/ProxymanApp/Proxyman/assets/126569739/c6e3915e-0cce-417d-b2db-76594f331799)
And I only request for it once in my browser.
Proxyman Version:4.8.0

**Comment by 907352qq** [comment]
I also tried to restore the factory settings, no effect.

**Comment by NghiaTranUIT** [comment]
@907352qq  Fixed: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_4.8.0_Fix_infinite_loop.dmg

![CleanShot 2023-05-25 at 15 02 06@2x](https://github.com/ProxymanApp/Proxyman/assets/5878421/55a1907d-e183-454a-888a-fcf6505ac0dd)

**Comment by 907352qq** [comment]
I used charles before, this is how I intended to use it:
![image](https://github.com/ProxymanApp/Proxyman/assets/126569739/7c6f1944-7246-4fff-b31a-d152fe381e46)
I now use a reverse proxy to solve the problem as well.
Thanks.

**Comment by NghiaTranUIT** [comment]
@907352qq you can check out the Reverse Proxy Tutorial: https://proxyman.io/posts/2023-03-22-How-to-use-Reverse-Proxy

Not sure what is the source of your Request? Is it from NodeJS Server, Python, or Ruby? If yes, instead of using the Reverse Proxy, which is complicated to setup, you can use the Automatic Setup: https://docs.proxyman.io/automatic-setup/automatic-setup

It helps you:
- ✅ 1 click to capture all HTTP & HTTPS traffic from your Terminal app.

NodeJS: Axios, got, superagent, fetch, and node-fetch
Python: http, https, aiohttp, requests
Ruby: http, net/http, net/htps, faraday, and httparty, fastlane
ElectronJS
cURL
