### ISSUE TITLE
我付费了，我希望所有地址都默认启用SSL

### ISSUE THREAD

**Issue by getxifan** [ProxymanApp/Proxyman#1673]
每个都需要单独设置，非常繁琐，我希望默认启用所有ssl

**Comment by getxifan** [comment]
没购买之前，开启SSL数量有限，但是我现在付费了，我希望给我吧所有网站都设置SSL，每次检查网站的时候，都需要手动设置一通，非常繁琐，也错过了最佳检测机会。

**Comment by NghiaTranUIT** [comment]
@getxifan You can open the SSL Proxying List in the Tool Menu -> Click on the + from the Include List -> Add Wildcard -> Use the `*` wildcard for all.

![CleanShot 2023-06-09 at 09 02 39@2x](https://github.com/ProxymanApp/Proxyman/assets/5878421/aaafd317-7ea7-404b-b577-3d17bc6415a3)

---------
I don't recommend it because it might:
- All Apple Traffic/Apps failed due to SSL Pinning Protection
- Consume more RAM memory.

**Comment by getxifan** [comment]
🎉非常感谢回复。解决了我的问题。
