### ISSUE TITLE
Does not intercept CLO 3D application traffic

### ISSUE THREAD

**Issue by Drovosek01** [ProxymanApp/Proxyman#1729]
## Description

Does not intercept CLO 3D application traffic

## Steps to Reproduce

1. Download a disk image from CLO3D https://www.clo3d.com/en/clo/download or mirror - https://1fichier.com/?t2fwaxz14wf00k0ej2mm
2. Move CLO_Standalone_OnlineAuth.app to the Application folder
3. Run Proxyman and install helper tool and certificate in the system in advance
4. Launch CLO_Standalone_OnlineAuth.app and log in with a real account or with fake data
5. View the Proxyman window

## Current Behavior

There are no lines from application CLO_Standalone_OnlineAuth.app or any other utilities that can be located inside the application

## Expected Behavior

In the Proxyman window there are lines from the application 123 and you can see what data is sent to the server when authorization is attempted and what data is coming

## Environment

- App version: Proxyman 4.9.0
- macOS version: macOS Monterey 12.6.4 Intel

**Comment by NghiaTranUIT** [comment]
Proxyman could not capture HTTPS traffic from the CLO3D app because it doesn't respect the system proxy and doesn't send the data to Proxy Server. You have to explicitly config it.

Here is what I've found on their document: https://support.clo3d.com/hc/en-us/articles/4417463135129-Proxy-Setup-for-CLO-Software-Login

See the Section: `Mac Users: Edit .zprofile file`

Here is the sample:
```bash
export CLO_HTTP_PROXY=127.0.0.1:9090
export CLO_HTTPS_PROXY=127.0.0.1:9090
```

**Comment by NghiaTranUIT** [comment]
@Drovosek01 it's from their document. If it doesn't work, it means either:
- You config incorrectly. Try again with `localhost:9090` instead of `127.0.0.1:9090`
- The Login API is intentionally hidden by the App Developer. Even though we set the HTTP Proxy.
