### ISSUE TITLE
Delete/trash button disconnects slack calls temporarily

### ISSUE THREAD

**Issue by jgallantgs** [ProxymanApp/Proxyman#1761]
## Description
Delete/trash button disconnects slack calls temporarily 

Similar to issue #1608 but I am not on a VPN.

https://github.com/ProxymanApp/Proxyman/assets/114911226/ba4618af-0e5c-4338-b4a9-875545ba2cfc

The video shows a slack call then pressing the button. For one or two frames you can see the slack error (a yellow banner). The issue lasts from clicking the button until you see speech indicators.

## Steps to Reproduce

1. Install fresh Proxyman
2. Add certificates to Mac and iOS Simulator
3. Make a call on Slack macOS native app
4. Click the delete/trash icon to reset logs

## Expected Behavior

Call should not drop.

## Environment

- Version 4.10.0 (49100)
- macOS version: 13.5.1 (22G90)

**Comment by NghiaTranUIT** [comment]
Hi @jgallantgs it's expected behavior because when "Clear Session", it will close all alive-connections, including the Slack Video Connection. After that Slack might try to reconnect it again.

To fix it, I suggest adding all Slack domains in the Tools Menu -> Proxy Setting -> Bypass Proxy Setting. You can add `*.slack.com` or any Slack domains that Proxyman captures.

It makes sure that Slack connection never goes through Proxyman -> No issue when closing session 👍

**Comment by jgallantgs** [comment]
Hey @NghiaTranUIT thank you for your response! There's a few domains and I tried with these two and still nothing. Slack is not coming up as a dedicated app either. Any other suggestions that may work for me?

<img width="1089" alt="image" src="https://github.com/ProxymanApp/Proxyman/assets/114911226/26086ba6-12d2-4902-8439-f5cbf191d95a">

**Comment by jgallantgs** [comment]
Thank you! 💪🏻
