### ISSUE TITLE
Proxyman 4.12.0 crashes on macOS 11.7.10

### ISSUE THREAD

**Issue by DaysJan** [ProxymanApp/Proxyman#1819]
## Description
I got a popup when I open Proxyman.
![CleanShot 2023-10-20 at 11 03 34@2x](https://github.com/ProxymanApp/Proxyman/assets/12560317/3d9f4c66-b115-4ba1-8278-47963768a569)

## Steps to Reproduce

1. Download Proxyman 4.12.0 from proxyman.io or Setapp.
2. Just open it.

## Current Behavior

Proxyman quit unexpectedly.

## Expected Behavior

Proxyman works well. :-)

## Environment

- App version: Proxyman 4.12.0
- macOS version: macOS Big Sur

## Problem Details and System Configuration

Refer to the attachment.[Problem Details and System Configuration.txt](https://github.com/ProxymanApp/Proxyman/files/13049566/Problem.Details.and.System.Configuration.txt)

**Comment by NghiaTranUIT** [comment]
@DaysJan you should try this Beta build: https://download.proxyman.io/beta/Proxyman_4.12.0_Fix_crash_on_AppCenter_on_macOS_11.dmg

Turn out the problem is from the AppCenter (Analytic). There is an internal crashes that happen on all macOS 11 or other. It works fine on macOS 12 or later.

Ref: https://github.com/microsoft/appcenter-sdk-apple/issues/2497#issuecomment-1727330207

**Comment by NghiaTranUIT** [comment]
I'm going to bump a new update and send to Setapp store soon 👍
