### ISSUE TITLE
App crashes when tapping `clear`

### ISSUE THREAD

**Issue by trinhngocthuyen** [ProxymanApp/Proxyman#2]
### Which Proxyman version are you using?
Proxyman 1.0.2 (1020)

### What OS Version are you using?
Mac 10.13.6

### Steps to reproduce this issue
1. Open the app
2. Tap "Clear"
<img width="655" alt="screen shot 2018-10-28 at 9 07 30 am" src="https://user-images.githubusercontent.com/8844044/47610820-671f0780-da91-11e8-89bc-c25fc0c88ae9.png">

One more highlight: upon subsequent launch of the app, I cannot access internet anymore

![crash_proxyman](https://user-images.githubusercontent.com/8844044/47610879-89655500-da92-11e8-85ae-f47f07950ac2.gif)

**Comment by NghiaTranUIT** [comment]
Thank for reporting that 👨‍💻. We admit that there are certain crashed bugs after we introduce new ProxymanCore. We're fixing it now.

Regarding Unable to access internet after the app crashed due to the Wifi Proxy Configuration. In order to fix it, just turn it off by open Wifi -> Preference -> Advance -> Proxies and **uncheck** HTTP and HTTPS Proxy.

In the future, we're planing to introduce child process to observer that crash and rollback the proxy appropriately 👍

**Comment by NghiaTranUIT** [comment]
Hello @trinhngocthuyen, here is the hot-fix build 
[Proxyman 1.0.2 (1022)](https://s3.us-east-2.amazonaws.com/proxyman/1022/Proxyman_1.0.2(1022).dmg)

We're going to release officially (with automation update) after fixing more couple bugs we found last week.

Thank you 👨‍💻

**Comment by NghiaTranUIT** [comment]
Done by official build [Proxyman 1.0.3](https://github.com/ProxymanApp/Proxyman/releases/tag/1.0.3)
