### ISSUE TITLE
Open Source?

### ISSUE THREAD

**Issue by astoilkov** [ProxymanApp/Proxyman#206]
Hi,

Have you considered open sourcing the app? Proxyman requires installing certificates and enabling permissions which involves trusting the developer behind the app. It also tracks sensitive data. Open sourcing the app will easily fix the trust problem and probably provide even more attention for the app.

Amazing app! Great UI/UX. This app has a lot of future.

**Comment by NghiaTranUIT** [comment]
Hey @astoilkov, 

I’m the author of Proxyman here 👏

Currently, we’re a [small team](https://proxyman.io/about-us), but we have a passion to ship a product with meticulous attention to detail based on our standard. Thus, we don’t have any plan for doing OSS yet. Maybe in the future, if we lose the interesting, we would consider doing open-source for the community.

Regarding privacy, we only track how many time users use particular features in order to have insight. It's essential for us to improve the features and drop out redundant things. Additionally, the self-signed certificate is generated in your local machine and all requests and responses go nowhere. What it's your machine, it's in your machine.

In the nutshell, I’m genuinely caring about your privacy as much as mine, so diagnostics and usage data are collected anonymously and it can not be used to identify the user.

It’s the fundamental rule of Proxyman that we completely respect it.

Thank you for reaching out. Don't hesitate to drop us a message at nghia@proxyman.io

**Comment by astoilkov** [comment]
Thanks for the quick and detailed response. I respect your decision for giving priority to higher quality software - I believe in that and it seems it works in your favor.

I am closing this issue.
