### ISSUE TITLE
Why I cannot see OPTIONS requests in the list?

### ISSUE THREAD

**Issue by sandrodz** [ProxymanApp/Proxyman#2063]
I expect OPTIONS requests to appear in the proxyman results.

This is to look at preflight requests from the browser. But non appear.

Is this a bug or a feature?

**Comment by NghiaTranUIT** [comment]
Basically, Proxyman will capture and decrypt OPTIONS requests (via HTTPS).

- Here is my test:

![CleanShot 2024-06-22 at 09 03 08@2x](https://github.com/ProxymanApp/Proxyman/assets/5878421/0b89d84a-9d55-4924-a4f7-74fe8e057b07)


May I ask: 
1. Do you can see other HTTPS (after the OPTIONS preflight) Requests/Responses? (To verify that you have installed & trust the certificate on your Mac, and enable SSL Proxying on your domain)
2. Do you see your OPTIONS request on the Google Chrome Network Tab? When I tested, all OPTIONS requests weren't called because they hit the cache. If I do "Empty Cache & Hard Reload", it will show in Proxyman and Chrome Network Tab (Other Tab)

**Comment by sandrodz** [comment]
You are absolutely right. It was the cache issue.

Thanks.
