### ISSUE TITLE
Your connection isn't private

### ISSUE THREAD

**Issue by fzlzjerry** [ProxymanApp/Proxyman#2096]
## Description

Since I've been using proxyman, google.com tells me Your connection isn't private, but I followed the tutorial on the website to install the certificate and trust it. I have a proxy software that listens at 127.0.0.1:7890. I also use external proxies in proxyman
## Steps to Reproduce

1.NET::ERR_CERT_COMMON_NAME_INVALID
2.
3.
4.

## Environment

- App version: Proxyman 5.6.1 Pro
- macOS version: macOS Sequoia

**Comment by NghiaTranUIT** [comment]
@fzlzjerry what happen if you stop using your proxy at `127.0.0.1:7890` and the External Proxy in Proxyman? Does it cause the bug?

If you are using the External proxy to your Proxy, please make sure your Proxy Server generates a certificate properly (and it should be installed & trusted to your Mac) too. Not just Proxyman.

**Comment by NghiaTranUIT** [comment]
second question. Do you visit `www.google.com` from Google Chrome or Firefox or what web browser?

**Comment by NghiaTranUIT** [comment]
@fzlzjerry just tested with macOS Sequoia

- Works fine with macOS Sequoia
- Can see HTTPS Response from www.google.com
=> I belive that the problem is your External Proxy. Please make sure the certificate (from your proxy Server) is installed & trusted on your Mac too.

![Screenshot 2024-07-23 at 14 51 23](https://github.com/user-attachments/assets/1b76f806-8806-441b-9e87-ebc2d841e2d6)

**Comment by fzlzjerry** [comment]
I know why, The Great Firewall did a man-in-the-middle hijacking of google and changed its certificate to facebook's
