### ISSUE TITLE
I can no longer debug apps on the AppStore. -SSL HandShake Error

### ISSUE THREAD

**Issue by tetsuyaEbina** [ProxymanApp/Proxyman#2100]
## Description

Hello
There is an app called "Maruhan App" on the App Store.
Until now, I have been using the app while debugging it using "proxyman" that you developed.
On 2024-07-30, I suddenly could not use it.
An SSL Handshake Error was displayed as an error, and although I tried various things, it did not resolve the issue.
I would like to request an investigation.
If you have any questions or need any additional information, please let me know.
Thank you in advance.

**Comment by NghiaTranUIT** [comment]
Can you try to reset the certificate in the Tool menu -> Reset, then installing the certificate again in the Tools menu -> Install for macOS ?

**Comment by tetsuyaEbina** [comment]
Thanks your advice!!
I have tried certification reset that you wrote.
But the error was not resolved at all....

**Comment by NghiaTranUIT** [comment]
then, I assume that it is from your app "Maruhan App" which has been updated and rejects Proxyman to intercept their data.

You can test it by:
1. Open Google Chrome / Safari
2. Visit `https://www.google.com`
3. Try to enable SSL Proxying this domain on Proxyman
4. Verify you can see HTTPS Request/Response of this domain
5. If it's good -> Proxyman is working ✅ 

Re-check with your app. If it's failed, I believe this app rejects Proxyman due to its security.

**Comment by tetsuyaEbina** [comment]
Oh ....
I guess that's the case. . .
It's probably being rejected for security reasons. . .
thank you.

**Comment by tetsuyaEbina** [comment]
Thanks your advice!!!
This issuse will close by me.
