### ISSUE TITLE
Unable to capture any network traffic from Zed editor

### ISSUE THREAD

**Issue by warpftl** [ProxymanApp/Proxyman#2115]
## Description
Proxyman does not show any network traffic from [Zed](https://zed.dev/).

## Steps to Reproduce

1. Start Proxyman
2. Open Zed editor
3. Try checking for updates from the menu bar: `Zed` -> `Check for Updates`
4. Try installing an extension:
	- Go to `Zed` -> `Extensions` from the menu bar
	- Install any extension such as a theme
5. Try chatting with an LLM through the assistant panel (open with `⌘?`)
6. No requests from Zed show up in Proxyman

## Expected Behavior

Proxyman should show some network traffic from Zed when it is making a network request such as when:
- Checking for an update
- Downloading an extension
- Chatting with an LLM

## Environment

- App version: Proxyman 5.7.0
- macOS version: macOS Ventura 13.5.2

**Comment by NghiaTranUIT** [comment]
@warpftl it's not a bug from Proxyman. 

No Zed's traffic is because Zed doesn't use the system proxy, all traffic goes directly to the Internet. So, no traffic is captured by Proxyman.

To fix it, we should find a Proxy Setting in Zed Editor.

Here is the solution:

```sh
http_proxy=http://192.168.1.128:9090 https_proxy=http://192.168.1.128:9090 zed project
```

You should replace the IP and port in the command with the IP & Port from the Proxyman Toolbar.

Ref: https://github.com/zed-industries/zed/discussions/7525
