### ISSUE TITLE
Cannot activate Pro license - closing the activation screen resets the serial

### ISSUE THREAD

**Issue by yar1vn** [ProxymanApp/Proxyman#2119]
## Description

After entering the license code and closing the Pro upsell screen the code is reset and the app reverts back to lite mode.

## Steps to Reproduce

1. Open Proxyman -> Proxyman Pro 
2. Click Activate License
3. Paste license and active
4. Close Pro screen
5. Open Pro screen and see license is not entered

## Environment
macOS Sonoma 14.6.1 (23G93)
Proxyman Version 5.7.0 (50700)

- App version: e.g Proxyman 3.9.0
- macOS version: e.g macOS Monterey

**Comment by NghiaTranUIT** [comment]
@yar1vn can you share with me your license key to support@proxyman.io ? I'd like to investigate it.

Currently, there are no similar reports, so I guess the problem is from your device. Tested again on my Mac Pro 15 20222, and it works fine. The license remains activating.

May I ask:
- What Macbook model that you're using? Is it Virtual machine or the real device?

**Comment by NghiaTranUIT** [comment]
It's fixed.
