### ISSUE TITLE
[feature] Ability to Override mac proxy on demand

### ISSUE THREAD

**Issue by shirshak55** [ProxymanApp/Proxyman#246]
Sometime while debugging android I would love to remove override from mac. Currently it is not possible because if i pause it will also pause for andriod which is painful.

**Comment by NghiaTranUIT** [comment]
I see your point @shirshak55. Currently, if we stop the Proxyman (by clicking on the Start/Stop button), it will stop the app and revert the HTTP proxy, which make those Remote Devices couldn't connect the Internet due to invalid Proxy address.

I've checked how Charles Proxy work, and it's actually not stop. The HTTP Proxy is still there, but at this time, Charles acts like a simple Proxy server (no record in left panel). Therefore, all remove devices, which is connecting to, are still working 👍 

Btw, thank for the request. I'm going to push it next two release 😄

**Comment by NghiaTranUIT** [comment]
All done 👍 

## 🤯 Changelogs 
- [x] The Start/Stop btn will start/stop recording flow. The macOS Proxy won't be affect. Remove device is still working
- [x] Introduce Override macOS Proxy in Proxy Setting menu. Able to switch ON OFF

**Comment by shirshak55** [comment]
wow u are working too fast :P

**Comment by NghiaTranUIT** [comment]
It's magic 😄
