### ISSUE TITLE
Response breakpoints not working as expected.

### ISSUE THREAD

**Issue by drekka** [ProxymanApp/Proxyman#274]
### Proxyman version? (Ex. Proxyman 1.4.3)

1.6.0

### macOS Version? (Ex. mac 10.14)

10.14.6

### Steps to reproduce 

1. Add a response only breakpoint rule to break on a localhost request.
2. Go back to Xcode and run the app.

### Expected behavior

Proxyman will break on the request coming back from the local host server and wait for the response to be edited.

### Actual behaviour

Proxyman displays the response in the Breakpoint window, then after about 5 seconds auto-continues before I've had a change to look or edit it.

### Some thoughts

Apart from the above bug, I also found the breakpoints UI a little confusing. For example, on the Breakpoints window there is a 'Add Rule' button below the list of breakpoints. At first I thought that I had to use this to add a break point. I didn't realised it was a a different thing b ecause it's position below the list suggested to me it would add something to it. 

I'd actually like to suggest changing the list of breakpoints to be a tree view, with the rules listed and the active breakpoint appearing (and disappearing) under the relevant rule. This would make easier and clearer to understand (IMHO), plus the add rule dialog would no be needed, just the dialog for editing a rule.

**Comment by NghiaTranUIT** [comment]
Thank for the feedback. I observers that the socket could be closed for some reasons (Timeout or bugs in the CocoaAsyncSocket) and it automatically close the Tunnel and the response is gone. Thus, It causes frustration.

I will investigate in this release.

------------
Regarding your thought, it's super valuable feedback. Thank you so much for the insight 👍 
I would make the breakpoint as a tree view, the note is the matched rule, and sub-list is list of breakpoint. Good sense for it 👍

**Comment by NghiaTranUIT** [comment]
Hot-fix build at https://github.com/ProxymanApp/Proxyman/issues/272#issuecomment-529538637 also including the UI change to indicate whenever the macOS proxy is enable/disable by the state button in Bottom-Left of windows.

At the first though, I would put it in the ToolBar, but its confusing to have 2 similar buttons. Thus, I would keep the simple as it is and move the indicate to bottom toolbar. 👍

**Comment by drekka** [comment]
I like the idea having a button. Probably just before the start/stop button.  I'm thinking you could use the standard power icon for starting and stopping proxying (installing settings) and continuing user the standard play/pause icons for starting and stopping recording.

**Comment by NghiaTranUIT** [comment]
Hey @drekka,

Sorry for being so long because I haven't reproduced it yet since that day.

Here is the hot-fix BETA build for you: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.9.3_Breakpoint_Issues.dmg

Technically, the request has connection: close so it close the connection immediately during editing the breakpoint => I override it to keep-alive and it works as we expected 🌮

I will rollout the fix in this week 👍

**Comment by drekka** [comment]
Thanks. That's great. I'll try and give it a go in the next eww days. Am a bit busy too at the moment :-)

**Comment by NghiaTranUIT** [comment]
Thank for that 👍

**Comment by drekka** [comment]
Unfortunately it's not working here. I ran a rule of "http://localhost%3A5050/*". ProxyMan hit the break point as expected, but didn't actually stop the response and the breakpoint disappears after about 5 - 10 seconds. 

I also noticed to that ports are using the characters "%3A" instead of ":", so I'm seeing URLs like http://localhost%3A5050/... instead of http://localhost:5050/... I had to use the "%3A" in the break points as well.

Finally something else which I'm not sure if it's me or not. If I click Certificate - Install Certificate on iOS Simulators ... it shows the root certs in this Mac as installed and trusted, but simulators as not being installed. I tap "Install to iOS Simulators" (wait for it to go green) then "Reset all iOS Simulators" and wait for them to reboot. But when I come back into this dialog it's still showing the simulators as needing certs. I also tried just adding the certs but it still shows them as not added when I come back to the certs dialog.

**Comment by NghiaTranUIT** [comment]
Regarding the iOS Simulator, it's a limitation because we don't know how many iOS simulators are installed the certificated. When you hit "Install to iOS Simulator", it means it would install to all visible simulators (other simulators (different iOS version or device types) are not installed).

I suppose that I should improve this screen by adding the Description to show that which devices are installed. For instance: ✅ Installed on iPhone X (iOS 11.1), iPhone X (iOS 10.1) simulators.
Thus, it's clear that you have installed successfully in certain device, but you can also install for the another if needed
 

**Comment by NghiaTranUIT** [comment]
Regarding the breakpoint, if it dismiss after 5-10 seconds, can you double check 
1. What is a `Connection` header in the request? (`keep-alive` or `close`)
2. How many timeout seconds?

Because if it dismiss after 5-10 seconds, it looks like the connection is break by timeout from the client.

**Comment by drekka** [comment]
Sorry, been very busy. Will get back on this when I can :-)

**Comment by NghiaTranUIT** [comment]
Thank for that @drekka.

Before the Breakpoint fix in Proxyman 1.10.0, Breakpoint would break as soon as it is connected (if the `Connection` header == `close`). Therefore, if it closes with a delay 5-10 seconds, it looks like by a Timeout.

**Comment by NghiaTranUIT** [comment]
Hi @drekka 
Here is the fix for Response Breakpoint https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.10.0_Fix_Breakpoint_Timeout.dmg

As the connection is closed due to timeout, so the Response will be disappears after 2 seconds. In this fix, I deliberately keep the connection alive and it should work 👍 

I will roll out officially the fix tmr.

**Comment by NghiaTranUIT** [comment]
Hey @drekka just friendly reminder that I released Proxyman 1.11.0, which actually fix the Breakpoint issues. Let check it out 👍

**Comment by drekka** [comment]
Thanks, will try it soon. Busy busy busy :-)

**Comment by drekka** [comment]
Just tried it in 1.13.1 and it looks to be working perfectly. Well done.

**Comment by NghiaTranUIT** [comment]
Thank you for informing 🎉
