### ISSUE TITLE
High Latancy/Resource Consumption

### ISSUE THREAD

**Issue by shirshak55** [ProxymanApp/Proxyman#332]
I used like proxyman and it seems there are some latancy added due to proxy. If i don't use proxy page loads fast but when i use proxy page loads so slow.

**Comment by NghiaTranUIT** [comment]
Hey, do you enable SSL for entire Safari or Google Chrome? Or just proxy as usual?

There is a known-issue that the noticeable delay happens when we try to enable entire Web Browser and I'm investigating it.

**Comment by shirshak55** [comment]
I think SSL should be default lol. Otherwise there is no reason to use proxy and every site we browse has SSL right. 

Yea I am trying to test what is happening in puppetter is it sending correct request and getting correct response or not.


I wish it had indicator like memory proxyman is using so we can know how much software is leaking

charles has that indication and it has too much leaks so i know i should close it and reopen it :D

**Comment by shirshak55** [comment]
yea proxyman has some problem if i use browser

```
Something bad happened TimeoutError: Navigation Timeout Exceeded: 120000ms exceeded
    at /Users/quantum/Desktop/code/asd/node_modules/puppeteer-core/lib/LifecycleWatcher.js:142:21
  -- ASYNC --
    at Frame.<anonymous> (/Users/quantum/Desktop/code/asd/node_modules/puppeteer-core/lib/helper.js:111:15)
    at Page.goto (/Users/quantum/Desktop/code/asd/node_modules/puppeteer-core/lib/Page.js:674:49)
    at Page.<anonymous> (/Users/quantum/Desktop/code/asd/node_modules/puppeteer-core/lib/helper.js:112:23)
    at /Users/quantum/Desktop/code/asd/src/modules/getdata.ts:57:22
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  name: 'TimeoutError'
```

**Comment by NghiaTranUIT** [comment]
The memory indicate in the bottom right bar would be implemented after the Remote Map, which is the next version. Sorry for the delay since there are couple high priority features and bugs 😄 

 For now, I suggest to we should only Enable SSL for certain domains, which you are trying to debug. Otherwise, Enable SSL for all would significantly impact the performance because the app is trying to decode all bodies.

**Comment by shirshak55** [comment]
@NghiaTranUIT hmm its strange because i have also enabled full ssl to every domain in charles which is not crashing but proxyman is not working meaning something is wrong right?

By the way I think with 90% of all sites being run on https ssl should be enabled by default and i think most people are interested in seeing request and response :D

**Comment by NghiaTranUIT** [comment]
I admit the the Proxyman Core is not mature yet. It's just first phase of the long term ProxymanCore. We're doing experiment to implement the v2, which is better performant and low-memory consuming, but it takes time since we're a small team 😃 

For a long term, Proxyman would interchangeable with Charles Proxy and our developer life is better, no more confusion due to bad UI/UX :"

Please stay tuned 👍 🌮

**Comment by shirshak55** [comment]
@NghiaTranUIT by the way where is problem in parsing https body? because i clearly don't see cpu usage of proxy which is good thing :D
