### ISSUE TITLE
[Feature] Show memory and cpu usage by proxy man

### ISSUE THREAD

**Issue by shirshak55** [ProxymanApp/Proxyman#394]
sometime application hangs while decoding ssl. It is useful if its really the proxy man ssl decoding  consequence it or computer is hanging because of other reason. Charles proxy has always shown the memory usage. 

May be `sbrk(0)` etc can be used to calculate existing heap usage as I don't think stack memory impacts too much.

**Comment by NghiaTranUIT** [comment]
There are some memory leaking I found couple days ago in ClientScanner class, which is responsible for scanning App with given `pid`. I forgot to release some pointer in C class 😢

Let me research how to get the memory usage and support it soon. Thank you for bumping it 👍

**Comment by NghiaTranUIT** [comment]
I found this gem: https://github.com/iglance/iGlance, which has all low-level I need, include Ram, Network, .... 

Credit to authors of iGlance 🙌

**Comment by NghiaTranUIT** [comment]
After bunch of trial and errors, it's the only way to get correct memory usage, which is presented in Xcode and Activity Monitor: https://stackoverflow.com/a/57315975/3127477 🙌 

It's time to support Network and Memory Usage in Proxyman 🌮

**Comment by NghiaTranUIT** [comment]
It's done @shirshak55 🙌 . I consider to support Memory and Network usage (not CPU), since those variables would be valuable and a option to opt-out if someone doesn't like it 😆

<img width="1578" alt="Screen_Shot_2020-02-22_at_18_11_17" src="https://user-images.githubusercontent.com/5878421/75091398-48eeec00-559f-11ea-9db6-557da60b84b5.png">
<img width="672" alt="Screen_Shot_2020-02-22_at_18_13_39" src="https://user-images.githubusercontent.com/5878421/75091404-5906cb80-559f-11ea-80c8-3f06f2f83567.png">

**Comment by shirshak55** [comment]
i saw it on twitter.

**Comment by shirshak55** [comment]
thanks again.

**Comment by shirshak55** [comment]
@NghiaTranUIT did u added cpu usage also?

**Comment by shirshak55** [comment]
hmm are u planning to add cpu usage?

**Comment by NghiaTranUIT** [comment]
I don't see any benefit to see the CPU so I remove it from the initial implementation.

**Comment by shirshak55** [comment]
actually it is useful when u do ssl parsing whether its proxy man or other is taking cpu. Most of the time when doing ssl monitoring i see proxyman using lot of cpu.
