### ISSUE TITLE
[BUG] Reversed ID sort causes selected row to change when request comes in

### ISSUE THREAD

**Issue by patrickbdev** [ProxymanApp/Proxyman#409]
### Proxyman version? (Ex. Proxyman 1.4.3)
1.16.0 (11600)

### macOS Version? (Ex. mac 10.14)
10.15.3 (19D76)

### Steps to reproduce 
1. Have requests coming in
1. Flip the ID sort
1. Select a row
1. Wait for another request to come in
1. Notice that the row you previously had selected has changed

### Expected behavior
Selected row doesn't change

### Screenshots (optional)
Demonstration: https://imgur.com/ftFuTHT

**Comment by NghiaTranUIT** [comment]
Thank you. I just opened the ticket too https://github.com/ProxymanApp/Proxyman/issues/408 😄

**Comment by NghiaTranUIT** [comment]
I will mention you when the bug is fixed 🙌

**Comment by patrickbdev** [comment]
Wow! We created it within a minute of each other 😮

**Comment by NghiaTranUIT** [comment]
Hey @patrickbdev 

Let try a beta build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.16.0_Fix_Selection_Jump.dmg

I change the behavior:
- If you’re selecting the first row and sort by ID then the new flow is appended at the top -> It will automatically select the top -> The Request/Response panel is updated. 
It’s our intention since you can get the new response without clicking on the top again. (Some users requested it) 
- If you’re select different rows (not the first), the selection is maintained (Fix your bug here).

I will release the fix tmr.

Please let me know if it works for you 🙌

**Comment by patrickbdev** [comment]
Thanks @NghiaTranUIT that does fix my problem.
I did want to make a comment about this change:
>If you’re selecting the first row and sort by ID then the new flow is appended at the top -> It will automatically select the top -> The Request/Response panel is updated.
It’s our intention since you can get the new response without clicking on the top again. (Some users requested it)

This doesn't seem to follow macOS convention. You can test this by:

1. Opening Finder
1. Selecting a row
1. Change the sorting by name
1. You'll notice that the item you had highlighted is still highlighted

I would recommend Proxyman's behaviour matching that what users are used to on macOS.

**Comment by NghiaTranUIT** [comment]
At the initial implementation, I did the same behavior with macOS. But it turns out that the case of Proxyman is slightly different when there are new requests are coming, and there is a need that I would get the last Request/Response data in the Content Panel.

Regarding your reproducible steps, I notice it's a small bug. When sorting, I completely reload the table -> The current selection is reset unexpectedly 😬 I'm fixing it now 🙌

**Comment by patrickbdev** [comment]
@NghiaTranUIT 
For this 
> Regarding your reproducible steps, I notice it's a small bug. When sorting, I completely reload the table -> The current selection is reset unexpectedly 😬 I'm fixing it now 🙌

Did you want me to open up a separate issue so we can close this one?

**Comment by NghiaTranUIT** [comment]
All done here @patrickbdev https://github.com/ProxymanApp/Proxyman/issues/417

Thank you for bumping it 🎉

**Comment by patrickbdev** [comment]
Thank you @NghiaTranUIT
