### ISSUE TITLE
[BUG] Broken URL Layout in Horizontal Mode

### ISSUE THREAD

**Issue by NghiaTranUIT** [ProxymanApp/Proxyman#436]
### Description
The URL TextField in Detail view is broken in Horizontal mode

### Proxyman version? (Ex. Proxyman 1.4.3)
Proxyman 1.18.1

### Steps to reproduce 
1. Set Horizontal Layout in Preference
2. Observe the URL Layout is broken

### Expected behavior
- Should work

To workaround, change the Layout mode to Vertical in Preference

### Screenshots (optional)
<img width="1405" alt="76226350-54553f00-6250-11ea-85a2-78359451c75a" src="https://user-images.githubusercontent.com/5878421/76482502-e58e0680-6446-11ea-9fc2-5dfb9f111131.png">

**Comment by crankygeek** [comment]
@NghiaTranUIT Just came here to file this. :)

I think it may be a slightly bigger issue having to do with how the individual views in that panel are resized. All three share a single resize control; the divider between Request and Response, which is pretty clunky.

Two additional notes about the URL layout - it's possible to collapse it to smaller than a single line, which effectively hides the text. Also, I think it should automatically/dynamically resize based on the size of the string in that view. Perhaps setting a max of ~ 4-5 lines.

I also wonder about maybe instead of having two cells, one for the type/status, and one for the URL, maybe they could be merged somehow, to free up a bit more horizontal space for longer request URLs?

**Comment by NghiaTranUIT** [comment]
Let checkout this BETA: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.18.1_Broken_UI_URL_TextField.dmg

The bug should be squashed 🙌 

And the Status StackView will update from Horizontal -> Vertical if the URL is too long and it saves us a little space as you wish 🍺 

<img width="1840" alt="Screen_Shot_2020-03-14_at_17_00_15" src="https://user-images.githubusercontent.com/5878421/76679759-8cc09880-6615-11ea-909f-8571afff87ce.png">

**Comment by crankygeek** [comment]
@NghiaTranUIT That looks great. And the status stacking is 👍. Thanks!
