### ISSUE TITLE
[Feature request][UX] Add names for map rules

### ISSUE THREAD

**Issue by josshad** [ProxymanApp/Proxyman#440]
### Proxyman version?
1.19.0

### macOS Version? 
10.14.6

### Introduction
Thanks for your work! :)

### Feature request
For ease of interaction with "Map local", "Map remote" tools, it would be convenient to be able to name them.
Very often, you need to switch between several rules for one endpoint. To distinguish them, you need to click on them all.

### Screenshots (optional)
![FR](https://user-images.githubusercontent.com/755348/76972673-facfcd00-693f-11ea-8f78-15ec40ea532f.png)

**Comment by NghiaTranUIT** [comment]
That's cool idea. I often struggle to determine which one is the one I have to enable during debugging 😄 The name field would be a life saver 🙌 

I will implement it in the next release 👍

**Comment by NghiaTranUIT** [comment]
Hey @josshad, let check out this beta build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.19.0_Name_Col_Remote_Local_Tools.dmg

I suppose the Name Column for Map Local and Map Remote Tool. For the rest tools (Breakpoint and Blacklist) I would support later since I'm refactoring the UI.
 
<img width="1255" alt="Screen Shot 2020-03-19 at 10 51 03" src="https://user-images.githubusercontent.com/5878421/77029888-98261200-69cf-11ea-99ab-3908f02c7a46.png">

**Comment by yeradis** [comment]
This is already released
