### ISSUE TITLE
Request Rewrite request/response feature

### ISSUE THREAD

**Issue by haikieu** [ProxymanApp/Proxyman#559]
### macOS Version: 10.15.5

Dear Proxyman Dev Team,

I've recently used the Proxyman, and felt so excited with it.
However comparing to some other tool, like Charles Proxy, It is lack of the crucial ability which help to rewrite the request/response with a custom header/body/status code, and so.

I know the app support the local mapping. But this is not always working well when the local content returned is static, so the needed response is not simulated exactly in many use cases. 

Hopefully you can consider this proposal, and soon implement it.
Thanks & regards.

**Comment by NghiaTranUIT** [comment]
I'm working on the Scripting (https://github.com/ProxymanApp/Proxyman/issues/557), which replace the ReWrite feature from Charles (because the ReWrite UI is complicated to use and it's not flexible)

Please check out the scripting ticket and see if it fulfills your current need? If not, please share with things that the Scripting doesn't work in your cases 😄

**Comment by NghiaTranUIT** [comment]
Hii @haikieu, please check out the latest build that has the Scripting Feature. Basically, it can do write your own Javascript code to rewrite the Request/Response's Header easily ❤️ 

Detailed at https://github.com/ProxymanApp/Proxyman/issues/329#issuecomment-682012601

**Comment by haikieu** [comment]
Thanks for replying and implementing a solution for it.
