### ISSUE TITLE
Sort by "time completed"

### ISSUE THREAD

**Issue by chipsfingrar** [ProxymanApp/Proxyman#720]
It would be very helpful if you could add a new column that shows the time at which a request completed (e.g. time + duration). I think this would be useful for debugging synchronisation problems/race conditions in multithreaded applications. For this to be useful, the precision of the timestamps would need a greater level of granularity, probably down to the millisecond or nanosecond.

**Comment by NghiaTranUIT** [comment]
Thanks for the request. I will support in the next release since it’s a trivial task 👍

**Comment by NghiaTranUIT** [comment]
Hey @chipsfingrar please check out this beta build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_2.14.2_Add_Time_Complete_Column_v2.dmg

- Add "Time Complete" column
- You can show/hide it by right-click on the column bar

<img width="1792" alt="Screen_Shot_2020-12-14_at_17_40_16" src="https://user-images.githubusercontent.com/5878421/102082217-225ab400-3e44-11eb-98e2-7dbb498339db.png">

<img width="434" alt="Screen_Shot_2020-12-14_at_17_40_24" src="https://user-images.githubusercontent.com/5878421/102082202-1d960000-3e44-11eb-9bff-07f861dcc352.png">

Sorry for being late since we're focusing on the iOS Proxyman 😄

**Comment by chipsfingrar** [comment]
Thank's a lot for adding this feature @NghiaTranUIT!
