### ISSUE TITLE
Enable SSL Proxying Not Working

### ISSUE THREAD

**Issue by ihomway** [ProxymanApp/Proxyman#756]
### Proxyman version? (Ex. Proxyman 1.4.3)
Version 2.16.0 (21600)

### macOS Version? (Ex. mac 10.14)
macOS Big Sur Version 11.1

### Steps to reproduce 

1. Open Proxyman
2. Open `google.com` in Safari
3. Select `https://www.google.com` in Proxyman
4. Click "Enable only this domain" in Response section
5. Response section flashed, but still show "Enable only this domain" and "Enable all domain from 'Safari'"
6. Click "Enable only this domain" again, and it said "Enabled"
7. Refresh Safari or re-open google.com
8. In the response section of the new request, it still said "Enable only this domain" and "Enable all domain from 'Safari'"

### Expected behavior
After SSL proxying enable, new response will be decrypted and displayed.

**Comment by ihomway** [comment]
My fault, option **Enabled SSL Proxying Tool** in *SSL Proxying List* not checked

**Comment by NghiaTranUIT** [comment]
Glad to know that you fix it 😄

**Comment by NghiaTranUIT** [comment]
@ihomway It's fixed with this beta build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_2.16.0_Fix_SSL_Proxying.dmg

No more this issue: `Response section flashed, but still, show "Enable only this domain" and "Enable all domain from 'Safari'"`

and it will enable the tool automatically to avoid this problem 🎉 

Thank you for the detailed report 👍

**Comment by ihomway** [comment]
Thank you, @NghiaTranUIT.
