### ISSUE TITLE
Question: Can we set Proxyman only track certain domain?

### ISSUE THREAD

**Issue by weitieda** [ProxymanApp/Proxyman#764]
### Proxyman version? (Ex. Proxyman 1.4.3)
2.16.1
### macOS Version? (Ex. mac 10.14)
10.15.6

Hi,

This is a great app and helps me a lot.

I found once setup, it seems like it's tracking all the request, I'm wondering can we limit Proxyman only tracks certain domain, e.g. only track the Pinned one?

Thanks,
Tieda

**Comment by NghiaTranUIT** [comment]
Hi @weitieda, by default, as soon as you open the Proxyman app, the app will override all HTTP/HTTPS Proxy config in the Network Preference. Therefore, all traffic will go through the Proxyman Proxy Server (localhost port 9090) and appear on the app.

To limit it, there are certain ways:
1. Limit it before it goes through the Proxy server. Please open Network Preference -> Wifi -> Advanced -> Proxies tab -> Enter the list that you don't want to go to the proxy server

<img width="780" alt="Screen_Shot_2021-01-26_at_08_36_56" src="https://user-images.githubusercontent.com/5878421/105787832-d4dc7580-5fb1-11eb-82dd-3bcda63423a9.png">

=> I'd not recommend this approach because It's cumbersome since you have to define all traffic that you **do not** want, not the list of the domain you need to track (It's opposite what you need) 😄 

2. Use Allow list tool https://docs.proxyman.io/advanced-features/whitelist
You can define which domains should appear on the app.

For example: define www.my-domain.com (ON in Include all Subpath checkbox) => Proxyman only records this domain and doesn't show other domains.

=> I'd recommend since it's easer 👍

**Comment by weitieda** [comment]
Hi Nighia,

Thanks for your details explanation! 👍🏼

Cheers,
Tieda
