### ISSUE TITLE
[Suggestion] Pre-configured filter to display errors

### ISSUE THREAD

**Issue by crankygeek** [ProxymanApp/Proxyman#770]
Version 2.16.1 (21610)
MacBook Pro (16-inch, 2019) macOS 10.15.7

I would like to see a pre-built filter for displaying only errors.

Currently, I select Status Code and Starts With "5" to view errors. I do this frequently enough that I've found myself wishing for a dedicated errors only view.

I'm not really sure what the UI for this could be. I at first imagined an option in the first dropdown, but then it occurred to me that I sometimes want to see errors only for particular URLs, so I'd still like to have access to the normal filters at the same time. Maybe a separate errors-only toggle button would work?

Thanks

**Comment by NghiaTranUIT** [comment]
It looks like Proxyman should support multiple filters soon 😄 (I have a plan #634, but we haven't shipped it yet)

I've also received some suggestions regarding "Quick Filter on Status code". I think that I can put these filter in the top bar (Like the screenshot), but hide it by default. Because I don't want to mess up the number of filter buttons 😄. We can enable it somewhere in the Preference I guess.
 
<img width="1074" alt="Screen_Shot_2021-01-30_at_08_31_35" src="https://user-images.githubusercontent.com/5878421/106343156-92c77280-62d6-11eb-9169-b53ffab49065.png">

@crankygeek how do you think?

**Comment by NghiaTranUIT** [comment]
Hey @crankygeek 

Please check out the beta build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_2.16.1_StatusCode_Font_Filters.dmg

From now, we can filter the Response by Status Code 😄 

> Currently, I select Status Code and Starts With "5" to view errors. I do this frequently enough that I've found myself wishing for a dedicated errors only view.

You can select 5xx Filter, then combining with URL filter as you wish 👍 

<img width="1680" alt="Screen_Shot_2021-02-01_at_14_32_49" src="https://user-images.githubusercontent.com/5878421/106429446-061ae100-649d-11eb-8fd2-168574322bbc.png">

<img width="1125" alt="Screen_Shot_2021-02-01_at_14_33_03" src="https://user-images.githubusercontent.com/5878421/106429453-0b782b80-649d-11eb-89be-ec7ec9b35e53.png">

**Comment by crankygeek** [comment]
@NghiaTranUIT That looks awesome, thanks!

**Comment by crankygeek** [comment]
@NghiaTranUIT Sorry, noticed something as soon as I replied (of course :)).

Once the status code filter is enabled, how do you turn it off? I tried clicking the currently applied filter, thinking it would toggle, but that doesn't appear to work. Neither does collapsing the filter.

I'd suggest the toggling, and also perhaps not allowing them to be collapsed if any filter is applied, or, if one is applied, collapsing still shows that filter enabled. This could help folks remember when they're applied. I realize that this would likely complicate that control, though.

As long as it's clear how to turn them off, that would be plenty.

Thanks again!

**Comment by NghiaTranUIT** [comment]
You can click on "All" Filter to clear the current filter.

It makes sense to support Toggle On/Off. I will check it out 👍

**Comment by NghiaTranUIT** [comment]
> I'd suggest the toggling, and also perhaps not allowing them to be collapsed if any filter is applied, or, if one is applied, collapsing still shows that filter enabled. This could help folks remember when they're applied. I realize that this would likely complicate that control, though.

Good point. I will follow this approach 👍 😄

**Comment by NghiaTranUIT** [comment]
Beta: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_2.16.1_Support_Toggle_FIlter_Button.dmg

From now, we can toggle Filter buttons because it's how the Toggle Button works 😄 

![2021-02-02 18 05 12](https://user-images.githubusercontent.com/5878421/106591992-87e43a80-6581-11eb-8af9-7a55120ae192.gif)

**Comment by crankygeek** [comment]
Sorry, meant to close this earlier!
