### ISSUE TITLE
Help - Is it possible to share a single script body between multiple Proxyman scripts?

### ISSUE THREAD

**Issue by crankygeek** [ProxymanApp/Proxyman#889]
### Proxyman version? (Ex. Proxyman 1.4.3)
Version 2.25.0 (22500)
### macOS Version? (Ex. mac 10.14)
MacBook Pro (16-inch, 2019) macOS 10.15.7

I have a script that I need to run with multiple endpoints with various Matching Rule criteria such as URL, Method, etc. The script body itself is the same regardless of the rules applied.

Is there a way to include an external file (.js, txt, whatever) as the script body on multiple Proxyman scripts? I tried saving it as a .js file and using the import function, but it doesn't appear to be executing the script.

I'm trying to create a suite of scripts that I can provide to my team that they can just toggle on and off as needed, rather than modifying the scripts directly.

Related, but separate, after adding 40 or so scripts, I'm really looking forward to folder organization in the Scripting tool (https://github.com/ProxymanApp/Proxyman/issues/739). I had a thought that perhaps adding other columns to the listing could be helpful. HTTP Method specifically comes to mind (I'm currently including it in the script title). I could also see a column for Response and Request checkboxes could be helpful, though I can see that might be a bigger lift.

Thanks as always!

- Jack

**Comment by NghiaTranUIT** [comment]
Hey @crankygeek it's possible to include an external JS file to multiple scripts by using Addons (https://docs.proxyman.io/scripting/write-your-own-addons). Basically, you can write your own addon and reuse it in different scripts as usual 👍 

Regarding the Rule Organizer, we're still working on it. The progress is slow since it changes many places and the core logic of the app, but we promise to ship it when it's done 😄

**Comment by crankygeek** [comment]
Got it. Thanks!
