### ISSUE TITLE
Modify response body snippet

### ISSUE THREAD

**Issue by Floperoid** [ProxymanApp/Proxyman#891]
I want to modify response using Scripting tool. My response is complicated json with nested objects and arrays that looks like that
payload: {
 ...........
  result{
  ........
  value[
   .......
   "something_i_want_to_change":"123",
   .......
  ]
  .........
 }
}

How can I replace "123" value to "321"?

**Comment by NghiaTranUIT** [comment]
Hey @Floperoid, since the body is an Object (Dictionary), so you can access the value as usual. For example:
```js
var body = response.body;

// Change it here
body.payload.result.value[0]. something_i_want_to_change = 123;

// Set it again
response.body = body
```

If it's too difficult to access a child node from a large JSON, you can export your Response first (Right-click on the Flow -> Export Response Body)

<img width="793" alt="Screen Shot 2021-05-15 at 8 05 17 PM" src="https://user-images.githubusercontent.com/5878421/118362225-dfe70000-b5b8-11eb-8d27-a44937ecc8f6.png">

Then set a `response.bodyFilePath` as a file path.
```js
function onResponse(context, url, request, response) {
 
  response.headers["Content-Type"] = "image/png";
  response.bodyFilePath = "~/Desktop/image.png";
 
  // Done
  return response;
}
```

Then, you can easily edit the JSON file with your favorited editor (VS Code or Sublime) 👍 

Ref: https://docs.proxyman.io/scripting/snippet-code#map-a-local-file-to-responses-body-like-map-local-tool-proxyman-2-25-0

**Comment by Floperoid** [comment]
Thank you a lot! Turns out It was my inadvertence
