### ISSUE TITLE
SSL Handshake Failed for Autodesk Fusion360

### ISSUE THREAD

**Issue by Drovosek01** [ProxymanApp/Proxyman#960]
### Proxyman version? (Ex. Proxyman 1.4.3)
2.31.0

### macOS Version? (Ex. mac 10.14)
10.14.6

### Steps to reproduce 
1. Download- https://dl.appstreaming.autodesk.com/production/installers/Fusion 360 Client Downloader.dmg
2. Run installer
3. Start listen https response from installer in ProxyMan

### Screenshots (optional)
![image](https://user-images.githubusercontent.com/29478700/129329581-7467065d-fb45-4a70-9c08-e0998c82a966.png)

**Comment by NghiaTranUIT** [comment]
Look like this app is using SSL Pinning, so it would reject all self-signed certificate from Proxyman

**Comment by NghiaTranUIT** [comment]
From your screenshot, I see that you are able to intercept some HTTPS traffic (id = 180, 181). It means the app is working properly.

However, all traffic from autodesk is failed. It is a high chance that the app rejects Proxyman certificate due to SSL-Pinning. From my experience, there is no way to intercept it unless you have their certificate 👍
